### ISSUE TITLE
Confusing chapter about Cloud Discovery

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-python-client#207]
See this chapter: https://github.com/hazelcast/hazelcast-python-client/blob/v3.12.3/README.md#58-enabling-hazelcast-cloud-discovery

The very first sentence: _The purpose of Hazelcast Cloud Discovery is to provide the clients the means to use IP addresses provided by hazelcast orchestrator_

As a new user I am confused: _What is "hazelcast orchestrator" and why should I care?_
I don't think users care about such details. Users wants to connect to a cluster. That's all.

Then it also says:
_To be able to connect to the provided IP addresses, you should use secure TLS/SSL connection between the client and members. Therefore, you should enable the SSL configuration as described in the TLS/SSL for Hazelcast Python Client section._

I don't understand it. There is no _should_. If I enabled TLS in the Cloud console then I _must_ enable it on the client side too. If I didnt not enable TLS on a server-side then I must not enable it on a client side.

**Comment by mdumandag** [comment]
I agree on both of the points. 

If I remember correctly, at the time we implemented cloud discovery for all clients, encrypted communication between clients and cloud members was a must but clearly things have changed. 

I will update this section and create issues for other clients since we all have the same documentation for it. 

Thanks for reporting this

**Comment by mdumandag** [comment]
Closing this since we won't do any development for 3.12.x. It is fixed in the master.
