### ISSUE TITLE
Proper way to do group_config.password in 4.0.0

### ISSUE THREAD

**Issue by TsvetanRangelov** [hazelcast/hazelcast-python-client#357]
Hello,
It seems that with the deprecation of ClientConfig, the parameters for group_config.password and group_config.name no longer exist. How can this be worked around with this release?

**Comment by mdumandag** [comment]
Hi @TsvetanRangelov 

The password of the group config was deprecated in Hazelcast 3.11 because it was providing a false sense of security. In IMDG 4.0, the deprecated password removed altogether.

The name of the group config can now be configured with the `cluster_name` keyword of the client. See the https://hazelcast.readthedocs.io/en/stable/client.html for other configuration options.

For the time being, this is the only option you can use. However, once we have a configuration to use custom credentials or some sort of security config in the Python client, you may use it to specify usernames and passwords while connecting to the cluster. We don't have an exact timeline for the implementation of this feature, but I am going to keep this issue open to track that.
