### ISSUE TITLE
connection_attempt_limit is not in latest version

### ISSUE THREAD

**Issue by prashantgupta123** [hazelcast/hazelcast-python-client#366]
Hi,

I saw that in the previous version connection_attempt_limit variable was there to attempt the connection.
But in the latest 4.0 version, I am not able to do so.
also I tried reconnect_mode=ReconnectMode.OFF this also does not work.
Can you please help me?

**Comment by mdumandag** [comment]
Hi @prashantgupta123 

This configuration option is removed in the 4.0 release since we introduced a more advanced exponential backoff feature.

You can use `cluster_connect_timeout` config option to limit the time it takes to connect to the cluster (both during the startup and reconnection). See the following discussion for more info about this option https://github.com/hazelcast/hazelcast-python-client/pull/346#pullrequestreview-581341359

**Comment by prashantgupta123** [comment]
Thank you for your quick response.
Yes, it worked for me currently.

**Comment by mdumandag** [comment]
Great to hear that, I am closing this issue then.

Feel free to reopen it or create new ones if you have further questions
