### ISSUE TITLE
Migrate the client to Python 3

### ISSUE THREAD

**Issue by waseem18** [hazelcast/hazelcast-python-client#73]
I've been working on making the client compatible with both Python 2 and 3 with respect the issue https://github.com/hazelcast/hazelcast-python-client/issues/29 

I feel it would be better if we can migrate the client to Python 3 instead of having Python 2 and 3 compatibility which is really tedious process (https://github.com/hazelcast/hazelcast-python-client/pull/72).

We can have the Python 3 version of the client on a different branch altogether so that it doesn't affect the current master code and also helps people in choosing the version they wanted to use.

Would like to know the thoughts of the community on this.

Thank You.

**Comment by waseem18** [comment]
@asimarslan @sancar Your thoughts on this please!

**Comment by sancar** [comment]
Hi @waseem18 , thanks for all the work you have done. 
Maintaining two different branches does not sound really good. As far as I understand that we are stuck because of`asyncore` to `asyncio` migration. Although I don't really understand the problem right now, I am sure we can figure it out. 
I think, even if we had to rewrite io logic we should not create two different branches. 

You probably already came across this one, but I am leaving this guide to us as future reference here: https://docs.python.org/3/howto/pyporting.html

**Comment by waseem18** [comment]
Thanks for the response @sancar 

Will check more if we can use `asyncore` in both Python 2 and 3.

**Comment by dbrimley** [comment]
Hi @waseem18 how are things progressing with the P3 port?  Super interested to hear how things are progressing.

**Comment by waseem18** [comment]
Hi @dbrimley 

Do you mean porting to Python 3 or supporting both Py2 and Py3?

I'm actually stuck with making the code compatible with both Py2 and Py3. 

If we want to port it to Python3, then I'm super excited for that. I haven't yet started though but will right away start on it if the community agrees for porting the code to Python 3.

Thanks :)

**Comment by dbrimley** [comment]
Do you have any details for what areas of code you're stuck on regarding the Py2/Py3 compatability work?

**Comment by waseem18** [comment]
The current version of the client uses asyncore (which is kind of deprecated) because of which it's really tedious to make the code compatible with both Python 2 and 3.

I tried porting asyncore to asyncio but in vain.

**Comment by dbrimley** [comment]
@asimarslan Do you have any suggestions as to how we can proceed and help out @waseem18 ?

**Comment by waseem18** [comment]
@dbrimley @asimarslan 

More details : It's tough to write Py2 and Py3 compatible code using `asyncore`. And `asyncore` is no longer being maintained. `asyncio` (only supports Py3) is into the game now.

Any help with using `asyncore` with both Py2 and Py3 would be appreciable.

Thanks

**Comment by asimarslan** [comment]
Hi @waseem18 ,

Thanks for your afford. 
I checked the asyncore vs asyncio libs. And asyncore still exists in python 3 for backward compatibility purpose, it says on [python api doc](https://docs.python.org/3.6/library/asyncore.html) that
>This module exists for backwards compatibility only. For new code we recommend using asyncio.

I believe we can use asyncore in python 3.x safely as it is part of the standard lib.  I can see that it is deprecated but in order to make things simpler we can use it in this very first python 3 support version. We can consider implementing other io libs like asyncio, libev, or twisted but these are future tasks.

Is our current asyncore code works with python 3 ? Can you share the problematic parts?

**Comment by MattNohelty** [comment]
Has there been any more progress on this recently?  If so, any target release date?  We would love to see the client run on Python 3 as well.

**Comment by waseem18** [comment]
@MattNohelty Unfortunately no progress has yet been made on this. Maintainers of this repo has the plan to have Hazelcast run on both Python 2 and Python 3 instead of migrating it to Python 3.

@asimarslan I've gone through your comment and right now as it's been  long time I don't exactly remember what the issue I was facing with asyncore. However I've closed my PR and would like to start fresh on making the client compatible with Py 2.

If I were to work on this, I would start with one file at a time - have it merged and move to another file. This way we can make considerable progress on making the client compatible.

We can use `tox` to test python version compatibility of the client.

 Let me know your thoughts on this.

cc: @dbrimley

**Comment by asimarslan** [comment]
Hi @waseem18,

I want to introduce @mdumandag . He's going to work with you on this issue.

On the issue; 
I think we can create a new dev branch for python 2&3 support so that you can freely send small PR's to be merged. At some point in time we can create a new build to run against python 3 to see the progress and merge the final work when the development is over.

**Comment by waseem18** [comment]
Hi @asimarslan @mdumandag

Sounds good!

Could you please create a `dev` branch? I'll start with some configuration setup either today or tomorrow.


Thanks

**Comment by asimarslan** [comment]
@waseem18 @mdumandag,
I've created `dev` branch for python 2&3 support development. You can send PR's to this branch and PR builder should just work.

**Comment by asimarslan** [comment]
I'm closing this issue on behalf of #29
