### ISSUE TITLE
funky behavior with the queue.take

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast-python-client#8]
we also found funky behavior with the queue.take. Sometimes, after the 120s timeout, further messages
get dequeued by take() but calling result() on the corresponding future blocks indefinitely. This usually occurs with the first or second message sent (offered) after the timeout.
(reported by @vsaldarriaga )

**Comment by mdumandag** [comment]
I believe this has been fixed with 4.0. We were mistakenly resolving invocations after the invocation timeout in 3.x series, despite no response being received from the server. That behavior is corrected in the later versions.

Also, this issue is quite old, and we haven't heard anything related to that or had test failures around it. So, I am going to close the issue.
