### ISSUE TITLE
Python api for map statistics (hazelcast cluster)

### ISSUE THREAD

**Issue by grafana2018** [hazelcast/hazelcast-python-client#82]
Hi,

As per below document we use to get map statistics in java :
http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Getting_Member_Statistics/Map_Statistics.html#page_Map+Statistics

We are implementing now the Python clien t for hazelcast cluster but not able find api for map statistics in python, please let us know is there anything lke that to get map statistics in pyhton by python-client.

Java --> LocalMapStats mapStatistics = customers.getLocalMapStats; 
Python  ----> ???

Regards,
Sreenath

**Comment by sancar** [comment]
LocalMapStats is a server only API. It returns the statistics for local only data. It shows number hits/gets of a map belonging to a locally owned partition. Since clients does not own a partition, clients does not support this method. 

In java client, only nearcache supported. Other methods return always zero(which seems odd, They should throw unsupported operation exception instead).

**Comment by grafana2018** [comment]
Thanks for the reply, Is this available in REST API's?

**Comment by sancar** [comment]
No, rest also does not have that. 
You can access the statistics via JMX on java.
http://docs.hazelcast.org/docs/3.10.1/manual/html-single/index.html#jmx-api-per-member
 Or you can view them in management center. 
http://docs.hazelcast.org/docs/management-center/3.10/manual/html/index.html#managing-maps
